spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinokio?serverTimezone=UTC
    username: root
    password: rhqckd
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update